version: '3.7'
services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/etc/trino
    networks:
      - trino-network

  es01:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.11.1'
    hostname: es01
    container_name: es01
    ports:
      - '9200:9200'
    volumes:
      - data01:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    networks:
      - trino-network

volumes:
  data01:
    driver: local

networks:
  trino-network:
    driver: bridge
